version: '3.8'
services:
    dev-db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_DATABASE=expenses_manager
          - MYSQL_ROOT_PASSWORD=root
        ports:
          - "3306:3306"
        restart: always
        volumes:
          - ./migration/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
volumes:
  dev-db:
    driver: local

